language: python
python:
  - "3.6"

services:
  - docker

environment:
  - DB_HOST=db
  - DB_NAME=app
  - DB_USER=postgres
  - DB_PASS=supersecretpassword
  - POSTGRES_DB=app
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=supersecretpassword


before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "
      python manage.py makemigrations core  &&
      python manage.py migrate core &&
      python manage.py migrate &&
      python manage.py test &&
      flake8"
